services:
  api-graphql-app:
    container_name: api-graphql-app
    build:
      context: .
      target: prod
      dockerfile: ./coffeedoor-api-graphql/Dockerfile
    env_file:
      - ./coffeedoor-api-graphql/.env.stage.docker
    ports:
      - "4444:4444"
    depends_on:
      - rabbitmq

  menu-rmq-ms:
    container_name: menu-rmq-ms
    build:
      context: .
      target: prod
      dockerfile: ./coffeedoor-menu-ms/Dockerfile
    env_file:
      - ./coffeedoor-menu-ms/.env.stage.docker
    depends_on:
      - rabbitmq
      - postgres-menu-rmq

  postgres-menu-rmq:
    container_name: postgres-menu-rmq
    image: postgres:latest
    ports:
      - "9901:5432"
    env_file:
      - ./coffeedoor-menu-ms/.env.stage.docker
    volumes:
      - pg_menu:/var/lib/postgresql/data

  adminer-menu-rmq:
    container_name: adminer-menu-rmq
    image: adminer
    ports:
      - 8801:8080

  user-rmq-ms:
    container_name: user-rmq-ms
    build:
      context: .
      target: prod
      dockerfile: ./coffeedoor-user-ms/Dockerfile
    env_file:
      - ./coffeedoor-user-ms/.env.stage.docker
    depends_on:
      - rabbitmq
      - postgres-user-rmq

  postgres-user-rmq:
    container_name: postgres-user-rmq
    image: postgres:latest
    ports:
      - "9903:5432"
    env_file:
      - ./coffeedoor-user-ms/.env.stage.docker
    volumes:
      - pg_user:/var/lib/postgresql/data
      
  adminer-user-rmq:
    container_name: adminer-user-rmq
    image: adminer
    ports:
      - 8803:8080

  rabbitmq:
    container_name: rabbitmq-broker
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.stage.docker

volumes:
  pg_user:
  pg_menu: